<a href="https://colab.research.google.com/github/v370r/projects/blob/master/All_Fesatures_housing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd

In [25]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [26]:
test_file = "/content/drive/MyDrive/kaggle/home-data-for-ml-course/train.csv"
data = pd.read_csv(test_file,index_col="Id") #making index column as start
data.describe()

        MSSubClass  LotFrontage  ...       YrSold      SalePrice
count  1460.000000  1201.000000  ...  1460.000000    1460.000000
mean     56.897260    70.049958  ...  2007.815753  180921.195890
std      42.300571    24.284752  ...     1.328095   79442.502883
min      20.000000    21.000000  ...  2006.000000   34900.000000
25%      20.000000    59.000000  ...  2007.000000  129975.000000
50%      50.000000    69.000000  ...  2008.000000  163000.000000
75%      70.000000    80.000000  ...  2009.000000  214000.000000
max     190.000000   313.000000  ...  2010.000000  755000.000000

[8 rows x 37 columns]

In [27]:
data.dtypes

MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 80, dtype: object

In [28]:
data.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice'],
      dtype='object')

In [29]:
data.head()

    MSSubClass MSZoning  LotFrontage  ...  SaleType SaleCondition SalePrice
Id                                    ...
1           60       RL         65.0  ...        WD        Normal    208500
2           20       RL         80.0  ...        WD        Normal    181500
3           60       RL         68.0  ...        WD        Normal    223500
4           70       RL         60.0  ...        WD       Abnorml    140000
5           60       RL         84.0  ...        WD        Normal    250000

[5 rows x 80 columns]

In [30]:
  data["LotArea"].dtype

dtype('int64')

In [31]:
%%time
data1 = pd.DataFrame()
for x in data.columns:
    data1[x] = data[x].astype("object")
data1.dtypes

CPU times: user 80.6 ms, sys: 910 µs, total: 81.5 ms
Wall time: 89.4 ms

In [32]:
data.describe()

        MSSubClass  LotFrontage  ...       YrSold      SalePrice
count  1460.000000  1201.000000  ...  1460.000000    1460.000000
mean     56.897260    70.049958  ...  2007.815753  180921.195890
std      42.300571    24.284752  ...     1.328095   79442.502883
min      20.000000    21.000000  ...  2006.000000   34900.000000
25%      20.000000    59.000000  ...  2007.000000  129975.000000
50%      50.000000    69.000000  ...  2008.000000  163000.000000
75%      70.000000    80.000000  ...  2009.000000  214000.000000
max     190.000000   313.000000  ...  2010.000000  755000.000000

[8 rows x 37 columns]

In [33]:
round(data["LotArea"].mean(),2)

10516.83

In [34]:
data.isnull().sum()

MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
Street             0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 80, dtype: int64

In [35]:
data.dropna(axis=0)

Empty DataFrame
Columns: [MSSubClass, MSZoning, LotFrontage, LotArea, Street, Alley, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, PoolQC, Fence, MiscFeature, MiscVal, MoSold, YrSold, SaleType, SaleCondition, SalePrice]
Index: []

In [36]:
data.isnull().sum()

MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
Street             0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 80, dtype: int64

In [37]:
Y = data.SalePrice

In [87]:
#feature_names = ["LotArea","YearBuilt","1stFlrSF","2ndFlrSF","FullBath","BedroomAbvGr","TotRmsAbvGrd"]
#x = data[feature_names]
x = data.select_dtypes(exclude="object")
x.describe(include= "all")

        MSSubClass  LotFrontage  ...       YrSold      SalePrice
count  1460.000000  1201.000000  ...  1460.000000    1460.000000
mean     56.897260    70.049958  ...  2007.815753  180921.195890
std      42.300571    24.284752  ...     1.328095   79442.502883
min      20.000000    21.000000  ...  2006.000000   34900.000000
25%      20.000000    59.000000  ...  2007.000000  129975.000000
50%      50.000000    69.000000  ...  2008.000000  163000.000000
75%      70.000000    80.000000  ...  2009.000000  214000.000000
max     190.000000   313.000000  ...  2010.000000  755000.000000

[8 rows x 37 columns]

In [88]:
X =x.dropna(how='any')

In [89]:
X.isnull().sum()

MSSubClass       0
LotFrontage      0
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
MasVnrArea       0
BsmtFinSF1       0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
TotRmsAbvGrd     0
Fireplaces       0
GarageYrBlt      0
GarageCars       0
GarageArea       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
SalePrice        0
dtype: int64

In [90]:
X.head()

    MSSubClass  LotFrontage  LotArea  ...  MoSold  YrSold  SalePrice
Id                                    ...
1           60         65.0     8450  ...       2    2008     208500
2           20         80.0     9600  ...       5    2007     181500
3           60         68.0    11250  ...       9    2008     223500
4           70         60.0     9550  ...       2    2006     140000
5           60         84.0    14260  ...      12    2008     250000

[5 rows x 37 columns]

# Model Fit

`Decision tree regressor`

In [91]:
x1 =X.drop(["SalePrice"],axis=1)

In [76]:
from sklearn.tree import DecisionTreeRegressor
iowa_model = DecisionTreeRegressor(random_state=2)

In [92]:
y = X.SalePrice

In [96]:
iowa_model.fit(x1,y)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=2, splitter='best')

In [97]:

predictions= iowa_model.predict(x1[:5])
predictions

array([208500., 181500., 223500., 140000., 250000.])

In [98]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y = train_test_split(x1,y,random_state=1,test_size=0.6) #train_test_split(X, y, train_size=0.8, test_size=0.2,random_state=0)
model = DecisionTreeRegressor(random_state=1)
model.fit(train_x,train_y)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=1, splitter='best')

In [99]:
train_x.shape

(448, 36)

In [100]:
test_x.shape

(673, 36)

In [101]:
predict_y= model.predict(test_x)
print(predict_y[:5])

[125500. 315000. 239000. 179900. 207500.]

In [102]:
from sklearn.metrics import r2_score  #r2 or coeefiecent of determination
r2_score(test_y,predict_y)

0.6073912037644725

In [103]:
from sklearn.ensemble import RandomForestRegressor
? RandomForestRegressor

In [50]:
"""
import os
if not os.path.exists("../input/train.csv"):
    os.symlink("../input/home-data-for-ml-course/train.csv", "../input/train.csv")  #(src,destination)
    os.symlink("../input/home-data-for-ml-course/test.csv",
  """

'\nimport os\nif not os.path.exists("../input/train.csv"):\n    os.symlink("../input/home-data-for-ml-course/train.csv", "../input/train.csv")  #(src,destination)\n    os.symlink("../input/home-data-for-ml-course/test.csv",\n  '

In [51]:
"""
from sklearn.ensemble import RandomForestRegressor

# Define the models
model_1 = RandomForestRegressor(n_estimators=50, random_state=0)
model_2 = RandomForestRegressor(n_estimators=100, random_state=0)
model_3 = RandomForestRegressor(n_estimators=100, criterion='mae', random_state=0)
model_4 = RandomForestRegressor(n_estimators=200, min_samples_split=20, random_state=0)
model_5 = RandomForestRegressor(n_estimators=100, max_depth=7, random_state=0)

models = [model_1, model_2, model_3, model_4, model_5]
print(models)
"""

"\nfrom sklearn.ensemble import RandomForestRegressor\n\n# Define the models\nmodel_1 = RandomForestRegressor(n_estimators=50, random_state=0)\nmodel_2 = RandomForestRegressor(n_estimators=100, random_state=0)\nmodel_3 = RandomForestRegressor(n_estimators=100, criterion='mae', random_state=0)\nmodel_4 = RandomForestRegressor(n_estimators=200, min_samples_split=20, random_state=0)\nmodel_5 = RandomForestRegressor(n_estimators=100, max_depth=7, random_state=0)\n\nmodels = [model_1, model_2, model_3, model_4, model_5]\nprint(models)\n"

In [105]:
%%time
from sklearn.metrics import mean_absolute_error
test_mae = abs(predict_y-test_y).mean()
test_mae

CPU times: user 1.07 ms, sys: 0 ns, total: 1.07 ms
Wall time: 980 µs

In [107]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from sklearn.tree import DecisionTreeRegressor
def get_mae(max_leaf_node,train_x,test_x,train_y,test_y):
  model = DecisionTreeRegressor(max_leaf_nodes=max_leaf_node,random_state=1)
  model.fit(train_x,train_y)
  predictions = model.predict(test_x)
  mae  = mean_absolute_error(test_y,predictions)
  return(mae)

In [108]:
%%time
ret = float("inf")
for max_leaf_nodes in range(2,1000,10):
  my_mae = get_mae(max_leaf_nodes,train_x,test_x,train_y,test_y)
  ret = min(ret,my_mae)
print(ret)

28718.93453295567
CPU times: user 954 ms, sys: 2.74 ms, total: 956 ms
Wall time: 966 ms

In [109]:
from sklearn.ensemble import RandomForestRegressor
def get_mae2(max_leaf_node,train_x,test_x,train_y,test_y):
  model = RandomForestRegressor(max_leaf_nodes=max_leaf_node,random_state=1)
  model.fit(train_x,train_y)
  predictions = model.predict(test_x)
  mae  = mean_absolute_error(test_y,predictions)
  return(mae)

In [110]:
%%time
ret = float("inf")
for max_leaf_nodes in range(2,1000,10):
  my_mae = get_mae2(max_leaf_nodes,train_x,test_x,train_y,test_y)
  ret = min(ret,my_mae)
print(ret)

20487.206730309128
CPU times: user 54 s, sys: 140 ms, total: 54.2 s
Wall time: 54.4 s

In [111]:
from sklearn.ensemble import RandomForestRegressor
rf_model = RandomForestRegressor(random_state =1)
rf_model.fit(train_x,train_y)
rf_predictions = rf_model.predict(test_x)
rf_predictions
r2_score(test_y,rf_predictions)

0.799437581511392

In [112]:
rf = RandomForestRegressor(n_estimators = 100,
                           n_jobs = -1,
                           oob_score = True,
                           bootstrap = True,
                           random_state = 42)
rf.fit(train_x, train_y)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=-1, oob_score=True,
                      random_state=42, verbose=0, warm_start=False)

In [113]:
!pip install rfpimp

Requirement already satisfied: rfpimp in /usr/local/lib/python3.6/dist-packages (1.3.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from rfpimp) (3.2.2)
Requirement already satisfied: stratx>=0.2 in /usr/local/lib/python3.6/dist-packages (from rfpimp) (0.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (from rfpimp) (1.1.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.6/dist-packages (from rfpimp) (0.22.2.post1)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from rfpimp) (1.18.5)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->rfpimp) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->rfpimp) (1.3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->rfpimp) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib->rfpimp) (0.10.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from stratx>=0.2->rfpimp) (1.4.1)
Requirement already satisfied: numba in /usr/local/lib/python3.6/dist-packages (from stratx>=0.2->rfpimp) (0.48.0)
Requirement already satisfied: colour in /usr/local/lib/python3.6/dist-packages (from stratx>=0.2->rfpimp) (0.1.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas->rfpimp) (2018.9)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->rfpimp) (0.17.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.1->matplotlib->rfpimp) (1.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from numba->stratx>=0.2->rfpimp) (50.3.2)
Requirement already satisfied: llvmlite<0.32.0,>=0.31.0dev0 in /usr/local/lib/python3.6/dist-packages (from numba->stratx>=0.2->rfpimp) (0.31.0)

In [115]:
from sklearn.metrics import r2_score
from rfpimp import permutation_importances
def r2(rf, train_x, train_y):
    return r2_score(train_y, rf.predict(train_x))
perm_imp_rfpimp = permutation_importances(rf, train_x, train_y, r2)

In [117]:
perm_imp_rfpimp

               Importance
Feature
OverallQual      0.766806
GrLivArea        0.121505
TotalBsmtSF      0.035720
LotArea          0.023426
OverallCond      0.017593
GarageArea       0.017210
FullBath         0.015107
BsmtFinSF1       0.014468
1stFlrSF         0.013432
YearRemodAdd     0.010340
LotFrontage      0.008302
GarageYrBlt      0.005111
YearBuilt        0.005085
2ndFlrSF         0.004853
GarageCars       0.004809
OpenPorchSF      0.004095
MasVnrArea       0.003360
TotRmsAbvGrd     0.003180
Fireplaces       0.003012
BsmtUnfSF        0.002543
WoodDeckSF       0.002140
MoSold           0.001666
HalfBath         0.001329
MSSubClass       0.001067
YrSold           0.001030
PoolArea         0.000869
EnclosedPorch    0.000837
BsmtFullBath     0.000790
BedroomAbvGr     0.000642
ScreenPorch      0.000322
BsmtFinSF2       0.000111
KitchenAbvGr     0.000091
MiscVal          0.000038
3SsnPorch        0.000038
LowQualFinSF     0.000030
BsmtHalfBath     0.000023

In [118]:
test_y.shape

(673,)

In [119]:
test_y.index.sort_values(ascending=True)[100:120]

Int64Index([207, 212, 213, 216, 217, 218, 220, 224, 231, 232, 234, 237, 239,
            240, 241, 243, 247, 248, 249, 252],
           dtype='int64', name='Id')

In [120]:
predict_y.shape

(673,)

In [121]:
output = pd.DataFrame({"Id":test_y.index,"cost":test_y,'SalePrice rf': rf_predictions,"sales trees":predict_y})
output.to_csv('/content/drive/MyDrive/kaggle/home-data-for-ml-course/submission.csv', index=False)